spring:
  application:
    name: cryptography

  datasource:
    url: jdbc:mysql://localhost:3306/crypto?allowPublicKeyRetrieval=true&useSSL=false
    username: admin
    password: 123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    hibernate:
        ddl-auto: update
